/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4c51ff2d-0979-49b3-b919-080afad9a055",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9oUUcu2Yl",
    "aws_user_pools_web_client_id": "7bbei58c1hck4rch9tpsk9f12u",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "aiforfun-front235230-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
